// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux; // CHANGED: Now returns linux config instead of throwing error
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDygJXW_LX1B_Pagp0EGgrf4czxJCoijsc',
    appId: '1:293389918942:web:c330f1b6244f1daa44184f',
    messagingSenderId: '293389918942',
    projectId: 'twittertrail-demo',
    authDomain: 'twittertrail-demo.firebaseapp.com',
    storageBucket: 'twittertrail-demo.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbN7VrCf3mpYgY3YM3UV_gAnCSQF1IN6A',
    appId: '1:293389918942:android:b5ab93ab6cb2597544184f',
    messagingSenderId: '293389918942',
    projectId: 'twittertrail-demo',
    storageBucket: 'twittertrail-demo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZEbiezia3TACq1kczVnV15p9czL3DsdE',
    appId: '1:293389918942:ios:08a568870579178e44184f',
    messagingSenderId: '293389918942',
    projectId: 'twittertrail-demo',
    storageBucket: 'twittertrail-demo.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZEbiezia3TACq1kczVnV15p9czL3DsdE',
    appId: '1:293389918942:ios:08a568870579178e44184f',
    messagingSenderId: '293389918942',
    projectId: 'twittertrail-demo',
    storageBucket: 'twittertrail-demo.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDygJXW_LX1B_Pagp0EGgrf4czxJCoijsc',
    appId: '1:293389918942:web:31f9723d33158bee44184f',
    messagingSenderId: '293389918942',
    projectId: 'twittertrail-demo',
    authDomain: 'twittertrail-demo.firebaseapp.com',
    storageBucket: 'twittertrail-demo.firebasestorage.app',
  );

  // ADDED: Linux configuration
  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyDygJXW_LX1B_Pagp0EGgrf4czxJCoijsc', // Same as web
    appId: '1:293389918942:web:c330f1b6244f1daa44184f', // Use web app ID
    messagingSenderId: '293389918942',
    projectId: 'twittertrail-demo',
    authDomain: 'twittertrail-demo.firebaseapp.com',
    storageBucket: 'twittertrail-demo.firebasestorage.app',
  );
}